[app]
name = "Sam's Clock"
category = "Badge"
wifi_preference = true

[entry]
class = "Clock"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-clock"
description = "Tell time on the Tildagon. See the README for what the buttons do"
version = "0.0.11"
